version: '3.9'
services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default/:/etc/nginx/conf.d/
      - ./dist/:/usr/share/nginx/html
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Surveyhubtrue
      MYSQL_DATABASE: manageuser
      MYSQL_PASSWORD: Surveyhubtrue
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Surveyhubtrue
      MYSQL_ROOT_PASSWORD: Surveyhubtrue
    ports:
      - '8080:80'
    depends_on:
      - db